// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFTuaU32EC_X52mEZ_B8QbFmPFEvl8r7o',
    appId: '1:633767186427:android:a3894e125f9c293827055e',
    messagingSenderId: '633767186427',
    projectId: 'bentz-stocks-cloud-computing',
    databaseURL: 'https://bentz-stocks-cloud-computing-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bentz-stocks-cloud-computing.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjc0SM0iWkT4y1X279X8qNKnnul1OV5w0',
    appId: '1:633767186427:ios:0fc7bfa0845d034227055e',
    messagingSenderId: '633767186427',
    projectId: 'bentz-stocks-cloud-computing',
    databaseURL: 'https://bentz-stocks-cloud-computing-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bentz-stocks-cloud-computing.appspot.com',
    iosClientId: '633767186427-ll4pv0vmvp3k5d701nlh01ublsl62lpa.apps.googleusercontent.com',
    iosBundleId: 'ro.bentz.bentzStocks',
  );
}
